//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selfblog.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class friendly_link:Selfblog.EF.BaseEntity.Root
    {
        public int id { get; set; }
        public string link_name { get; set; }
        public string link_url { get; set; }
        public string link_logo { get; set; }
        public Nullable<int> show_order { get; set; }
    }
}
