//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selfblog.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_comment:Selfblog.EF.BaseEntity.Root
    {
        public int c_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> comment_time { get; set; }
        public int article_id { get; set; }
        public Nullable<int> rec_status { get; set; }
        public int status { get; set; }
        public int rec_id { get; set; }
        public Nullable<int> floor { get; set; }
    }
}
